//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSMS_Server_Phase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"            using (SqlConnection sql = new SqlConnection())
            {
                sql.ConnectionString = ConfigurationManager.ConnectionStrings[""bid_dbConnectionString1""].ConnectionString;
                sql.Open();
                SqlCommand sqlcommand = new SqlCommand(listcategory, sql);
                SqlDataReader reader = sqlcommand.ExecuteReader();
                catg_id.Items.Clear();
                while (reader.Read())
                {
                    ListItem itm = new ListItem(reader.GetString(1), reader.GetInt32(0).ToString());
                    catg_id.Items.Add(itm);
                }
                reader.Close();
                sql.Close();
            }
")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\Backup_11_11_2010.md" +
            "b")]
        public string Backup_11_11_2010ConnectionString {
            get {
                return ((string)(this["Backup_11_11_2010ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=./;Initial Catalog=rtsmsdb;Integrated Security=True")]
        public string SQLServerRTSMSDBConnectionString {
            get {
                return ((string)(this["SQLServerRTSMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=./;Initial Catalog=rtsmsdb;Integrated Security=True")]
        public string RSSReaderConnectionString {
            get {
                return ((string)(this["RSSReaderConnectionString"]));
            }
        }
    }
}
